language: ruby
rvm:
  - 2.1
before_script:
  - bundle update
install:
  - bundle install
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --empty-alt-ignore --check-html --url-ignore [ '*/js/*' ]

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
