# Site settings
title: Academic Revisions
index_title: Academic Revisions # same as title in index.html file, so that custom description can be set in page.html layout.
blog_title: Academic Revisions
header-img: img/home-bg.jpg
email: 
copyright_name: 
description: "Academic Revisions & Translations"
baseurl: "" #base url is for when the site is not at the root but at some subdirectory.
url:  #only used in disque comments for now
github_username:  
facebook_username:  
email_username: 
# used to estimate reading time
wpm: 180

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed]
